### ISSUE TITLE
Suggestion: negation in search parameters

### ISSUE THREAD

**Issue by timbennett** [pushshift/api#1]
Here's a sample query for comments containing links to imdb.com: https://api.pushshift.io/reddit/search/comment/?q=imdb.com/name/

The results are dominated by a bot ([/u/boltrop](https://www.reddit.com/user/boltrop)). In this and similar use cases, it would be useful to set a parameter to filter out one or more usernames. 

I'm not sure of the best way to do this, but I thought either a new parameter like "notauthor=boltrop", or allowing negation in a parameter e.g. "author=!boltrop". 

In this use case, I know I can currently solve the problem by collecting all the results and filtering by username later. But this wouldn't work for people attempting to exclude a user from being counted in their aggregations (e.g. people might want to exclude AutoModerator posts).

**Comment by pushshift** [comment]
I think this is a great idea and worth implementing so I'll put it towards the top of the list and start working on it.  I like author=!some_author idea the best between the two alternatives you suggested.  It keeps the parameters count down and it works well with Reddit author names.  The "!" character can't be present in an author or subreddit name so it will work for those.  For standard "q" (query term) searches, the "!" is ignored by Elasticsearch with the current configuration, so it would work there as well.  

I'll go ahead and implement this for author first since that seems to be the best use case to get rid of bots manually.

**Comment by pushshift** [comment]
This has been implemented.  (See commit in develop branch:  https://github.com/pushshift/api/commit/022e7dd1a1a15b5a513b598fc6ccf00508c566d5)

Test:

https://api.pushshift.io/reddit/search/comment/?q=imdb.com/name/&author=!boltrop  (Returns everything but that bot)

Also, you can combine multiple negated authors along with authors that should match (i.e. author=include_this_1,include_this_2,!do_not_include_this_1,!do_not_include_this_2)

**Comment by pushshift** [comment]
Actually, combining negated with non_negated doesn't make sense since asking for specific authors already negates all others not asked for -- but the code still works anyway and will give negation precedence (i.e. https://api.pushshift.io/reddit/search/comment/?q=imdb.com/name/&author=!boltrop,boltrop returns nothing but would be a non-nonsensical request anyway)  :)

**Comment by timbennett** [comment]
Thanks!
